# Generated by Django 6.0.5 on 2026-05-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_achievement_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dragon_frozen',
            field=models.BooleanField(default=False, verbose_name='Дракон заморожен'),
        ),
        migrations.AddField(
            model_name='profile',
            name='frozen_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заморожен с'),
        ),
        migrations.AddField(
            model_name='profile',
            name='missed_days',
            field=models.IntegerField(default=0, verbose_name='Пропущено дней подряд'),
        ),
    ]
